SELECT 
    game_id,
    game_title,
    game_date,
    event_num,
    "period",
    seconds_elapsed,
    event_type_last,
    event_team_last,
    zone_code_last,
    seconds_since_last,
    strength_state,
    event_type,
    "description",
    event_team_abbr as team,
    event_player_1_name as skater,
    event_player_2_name as skater_2,
    event_player_3_name as skater_3,
    shot_type,
    zone_code,
    x,
    y,
    x_fixed,
    y_fixed,
    x_adj,
    y_adj,
    away_score,
    home_score,
    away_on_1,away_on_2,away_on_3,away_on_4,away_on_5,away_goalie,away_coach,
    home_on_1,home_on_2,home_on_3,home_on_4,home_on_5,home_goalie,home_coach,
    offwing,
    xG

FROM read_parquet([
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20102011.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20112012.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20122013.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20132014.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20142015.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20152016.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20162017.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20172018.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20182019.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20192020.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20202021.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20212022.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20222023.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20232024.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20242025.parquet"
    ])