SELECT 
    season,
    game_id,
    game_title,
    game_date,
    event_num,
    "period",
    seconds_elapsed,
    seconds_since_last,
    strength_state,
    event_type,
    "description",
    event_team_venue as venue,
    event_team_abbr as team,
    event_player_1_id as skater_id,
    event_player_2_id as skater_id_2,
    event_player_3_id as skater_id_3,
    event_goalie_id as goalie,
    shot_type,
    zone_code,
    x_fixed,
    y_fixed,
    x_adj,
    y_adj,
    away_score,
    home_score,
    away_on_1_id,away_on_2_id,away_on_3_id,away_on_4_id,away_on_5_id,away_on_6_id,away_goalie_id,
    home_on_1_id,home_on_2_id,home_on_3_id,home_on_4_id,home_on_5_id,home_on_6_id,home_goalie_id,
    penalty_duration,
    xG

FROM read_parquet([
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20102011.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20112012.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20122013.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20132014.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20142015.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20152016.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20162017.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20172018.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20182019.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20192020.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20202021.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20212022.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20222023.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20232024.parquet",
    "https://f005.backblazeb2.com/file/weakside-breakout/pbp/nhl_pbp_20242025.parquet"
    ])